### ISSUE TITLE
maxConnectTime

### ISSUE THREAD

**Issue by GeoAcad3my** [jcmb/NTRIP#3]
Hello jcmb,

In line 141 of file NtripClient.py, where the variable maxConnectTime is being parsed into the function timedelta, I think you should call the variable over the self instance here. 

            EndConnect=datetime.timedelta(seconds=self.maxConnectTime) # should it not be like this? 

The same for line 209

            if self.maxConnectTime: 

This issue does not appear if the script NtripClient.py is executed, because the variable maxConnectTime is already defined within the `if __name__ == '__main__'` block outside the class. As soon as the class will be imported into another python file, the problem comes up. 

Best regards
Lukasz

**Comment by jcmb** [comment]
Fixed this issue, and it was generally not working from the script either.

Fixed this and a few other items in 0.3
